### ISSUE TITLE
LoadError (cannot load such file -- twitch-chat)

### ISSUE THREAD

**Issue by JamieREvans** [EnotPoloskun/twitch-chat#1]
I'm trying to use this gem, but I can't seem to 'require' it in my controller class

Here is the top of my controller:

```
class ChatsController < ApplicationController

    require 'net/http'
    require 'uri'
    require 'twitch-chat'
```

And here is the error:

```
LoadError (cannot load such file -- twitch-chat):
  app/controllers/chats_controller.rb:5:in `<class:ChatsController>'
  app/controllers/chats_controller.rb:1:in `<top (required)>'


  Rendered /Users/Jamie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_source.erb (5.1ms)
  Rendered /Users/Jamie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (2.2ms)
  Rendered /Users/Jamie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (9.0ms)
  Rendered /Users/Jamie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (0.9ms)
  Rendered /Users/Jamie/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/diagnostics.html.erb within rescues/layout (86.5ms)
```

Why can't I include this gem in my controller? It's bundled into my application ('bundle install' _does_ list it as an installed gem)

**Comment by TheDevster** [comment]
@JamieREvans, it's require 'twitch/chat' ... he needs to update his notes.  lol

**Comment by EnotPoloskun** [comment]
was fixed in https://github.com/EnotPoloskun/twitch-chat/pull/2
