### ISSUE TITLE
LoadError: cannot load such file -- eventmachine

### ISSUE THREAD

**Issue by 1v** [EnotPoloskun/twitch-chat#3]
When adding gem to gemfile:
```
gem 'twitch-chat', :require => 'twitch/chat'
```
I have this error when starting server:
```
LoadError: cannot load such file -- eventmachine
/home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/user/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/user/.rvm/gems/ruby-2.3.1/gems/twitch-chat-0.0.1/lib/twitch/chat.rb:1:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/home/user/www/app/config/application.rb:7:in `<top (required)>'
/home/user/www/app/Rakefile:4:in `require'
/home/user/www/app/Rakefile:4:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.3.1/bin/rake:23:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
/home/user/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
/home/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by 1v** [comment]
Finally got it working! See my changes https://github.com/EnotPoloskun/twitch-chat/compare/master...1v:master

And in Gemfile I added just:
```
gem 'twitch-chat'
```

**Comment by AlexWayfer** [comment]
So, should we close this issue?
